name: alex_k_test_cats_facts
description: Alexk Karpov test facts
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  either_dart: ^0.3.0
  shared_preferences: ^2.0.20
  internet_connection_checker: ^1.0.0+1
  data_connection_checker_nulls: ^0.0.2
  equatable: ^2.0.5
  retrofit: ^4.0.1
  logger: any
  hive: ^2.2.3
  dio: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  intl: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3


flutter:
  uses-material-design: true
